spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password
app:
  rabbitmq:
    autoInit: true
    # reset: true

    queues:
      - name: queue1
        exchange: directExchange
        routingKey: rk1
      - name: queue2
        exchange: directExchange
        routingKey: rk2
      - name: queue3
        exchange: fanoutExchange
        routingKey: ""
