spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: medusa

application:
  rabbitmq:
    queue-name: demo-queue
    max-concurrent-consumers: 5  # 可以配置同時處理的 message 數量