# -----------------------------------------------------------------------------
# Server (Tomcat)
# -----------------------------------------------------------------------------
## Product Metadata
server:
  port: ${port:8080}

# -----------------------------------------------------------------------------
# logback
# -----------------------------------------------------------------------------
logging:
  path: ./logs
  level.com.gtcafe.rws.booter: INFO


app.debug: true