spring:
  # Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:messageboard
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  # Redis Configuration for Development (using embedded Redis)
  data:
    redis:
      host: localhost
      port: 6379

# Logging Configuration for Development
logging:
  level:
    root: INFO
    com.messageboard: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG