openapi: 3.0.2
info:
    title: R Web Service - RWS v1.0
    description: >-
        This is a sample Pet Store Server based on the OpenAPI 3.0
        specification.  You can find out more about

        Swagger at [http://swagger.io](http://swagger.io). In the third iteration
        of the tenants store, we've switched to the design first approach!

        You can now help us improve the API whether it's by making changes to the
        definition itself or to the code.

        That way, with time, we can improve the API in general, and expose some
        of the new features in OAS3.

    termsOfService: "http://swagger.io/terms/"
    contact:
        email: admin@gtcafe.com
    license:
        name: Apache 2.0
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    version: 1.0.17
externalDocs:
    description: Find out more about Swagger
    url: "http://swagger.io"
servers:
    - url: /api/v1alpha
tags:
    - name: account
      description: Account in the R Web Services

    - name: tenant
      description: Multi-tenancy
      externalDocs:
          description: Find out more
          url: "http://swagger.io"

    - name: user
      description: User in the tenant

    - name: extension
      description: Extension services
      externalDocs:
          description: Find out more
          url: "http://swagger.io"

paths:
    "/account":
        $ref: "./paths/operate-account-no-id.yaml"

    "/account/login":
        $ref: "./paths/login-account.yaml"

    "/account/logout":
        $ref: "./paths/logout-account.yaml"

    "/account/{accountName}":
        $ref: "./paths/operate-account.yaml"

    ##
    "/tenant":
        $ref: "./paths/operate-tenant-no-id.yaml"

    "/tenants/{tenantId}":
        $ref: "./paths/operate-tenant.yaml"

    "/user":
        $ref: "./paths/operate-user-no-id.yaml"

    "/user/loginTenant":
        $ref: "./paths/login-tenant.yaml"

    "/user/logoutTenant":
        $ref: "./paths/logout-tenant.yaml"

    "/user/{username}":
        $ref: "./paths/operate-user.yaml"

components:
    schemas:
        com.gtcafe.rws.entity.Account:
            $ref: "./components/entity/Account.yaml"

        com.gtcafe.rws.entity.User:
            $ref: "./components/entity/User.yaml"

        com.gtcafe.rws.entity.Tenant:
            $ref: "./components/entity/Tenant.yaml"

        com.gtcafe.rws.entity.ApiResponse:
            type: object
            properties:
                code:
                    type: integer
                    format: int32
                type:
                    type: string
                message:
                    type: string

    requestBodies:
        com.gtcafe.rws.entity.request.Tenant:
            description: Pet object that needs to be added to the store
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/com.gtcafe.rws.entity.Tenant"

        com.gtcafe.rws.entity.request.UserArray:
            description: List of user object
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: "#/components/schemas/com.gtcafe.rws.entity.User"

    securitySchemes:
        rws_auth:
            type: oauth2
            flows:
                implicit:
                    authorizationUrl: "https://tenantstore3.swagger.io/oauth/authorize"
                    scopes:
                        "write:tenants": modify tenants in your account
                        "read:tenants": read your tenants

        api_key:
            type: apiKey
            name: api_key
            in: header
