spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password

app:
  rabbitmq:
    autoInit: true
    # reset: true

    queues:
      - name: queue1
        exchange: directExchange
        routingKey: rk1
      - name: queue2
        exchange: directExchange
        routingKey: rk2
      - name: queue3-fantout
        exchange: fanoutExchange
        routingKey: ""

      - name: queue4-fantout
        exchange: directExchange
        routingKey: rk4

      - name: queue5-fantout
        exchange: directExchange
        routingKey: rk5
