# -----------------------------------------------------------------------------
# logback
# -----------------------------------------------------------------------------
# logging:
  # path: ./logs
  # level.com.gtcafe.asimov: INFO

