
### ---
POST http://localhost:8080/article
Content-Type: application/json

{
    "subject": "Test Article",
    "content": "This is a test article.",
    "createdAt": "2024-06-16T12:00:00"
}


### --
GET http://localhost:8080/article?pageSize=2&cursor=0
Content-Type: application/json


### ---
PATCH http://localhost:8080/article/2
Content-Type: application/json

{
    "subject": "update",
    "content": "update."
}
