# -----------------------------------------------------------------------------
# Server (Tomcat)
# -----------------------------------------------------------------------------
## Product Metadata
server:
  port: ${port:8080}

# # -----------------------------------------------------------------------------
# # Sprinboot 3.1
# # -----------------------------------------------------------------------------
# spring:
#   application:
#     name: @pom.artifactId@





