version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["mongod", "--noauth"]
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  cache_redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    volumes:
      - ./.docker-data/cache_redis:/data
    networks:
      - net1


  cache-adminer_phpRedisAdmin:
    image: erikdubbelboer/phpredisadmin:1.19
    ports:
      - 9998:80
    environment:
      REDIS_1_HOST: cache_redis
      REDIS_1_NAME: localhost
    networks:
      - net1


volumes:
  mongo_data:
    driver: local

networks:
  net1:
    driver: bridge
