server:
  port: 8080

# spring:
#   data:
#     redis:
#       database: 0
#       host: localhost
#       port: 6379
#       # password: password
#       # timeout: 60000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp
    username: myuser
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 3000
      validation-timeout: 3000


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

## 新增
management:
  endpoints:
    web:
      exposure:
        include: health
        show-details: always

    health:
      show-details: always

# 自定義健康檢查
  health:
    custom:
      enabled: true

# Actuator 健康檢查策略
    defaults:
      enabled: true
    db:
      enabled: true
