spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school

    redis:
      host: localhost
      port: 6379

  session:
    # 存儲類型，可選值有 none, jdbc, redis, hazelcast, mongodb
    store-type: redis

    # session 超時時間，預設 30 分鐘
    timeout: 30m

    # 是否在啟動時創建 session 存儲需要的表/結構
    initialize-schema: always

    # Redis 配置
    redis:
      namespace: asimov:session
      flush-mode: on-save
      cleanup-cron: "0 * * * * *"

server:
  servlet:
    session:
      cookie:
        # Cookie 名稱，預設 JSESSIONID
        name: rSessionId

        # Cookie 持續時間，默認為 -1 (瀏覽器關閉後失效)
        max-age: 3600

        # 是否僅通過 HTTPS 傳輸
        # secure: true

        # 是否僅限 HTTP 訪問（不允許 JavaScript 訪問）
        # http-only: true

        # Cookie 路徑
        # path: /

        # Cookie 域
        # domain: example.com

        # Cookie SameSite 屬性
        # same-site: lax

      # 是否持續性 session，預設 false
      # persistent: false

      # 追蹤模式，可選值有 cookie(默認)、url、ssl
      # tracking-modes: cookie

      # 超時時間，預設 30 分鐘
      timeout: 30m