# -----------------------------------------------------------------------------
# Server (Tomcat)
# -----------------------------------------------------------------------------
## Product Metadata
server:
  port: ${port:8080}

  # Disable Whitelabel Error Page
  # see: https://websparrow.org/spring/how-to-resolve-whitelabel-error-page-in-spring-boot
  error:
    whitelabel:
      enabled: false


# -----------------------------------------------------------------------------
# Sprinboot 3.1
# -----------------------------------------------------------------------------
## see: https://stackoverflow.com/questions/26585959/how-to-disable-spring-boot-logo-in-stdout
#spring.main.banner-mode=off
spring:
  application:
    name: @pom.artifactId@

# -----------------------------------------------------------------------------
# logback
# -----------------------------------------------------------------------------
logging:
  path: ./logs
  level.com.gtcafe.rws.booter: INFO

app:
  rabbitmq:
    exchange: app.exchange1.topic1
    queue: app.queue
    routingkey: app.routingkey