{
 "title": "JVM Metrics Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP 請求錯誤率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"5*\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 響應時間分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"DELETE\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"PUT\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(process_cpu_usage[5m])", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Create Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "rate(tasks_created_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "rate(tasks_completed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM 線程數量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "Heap Memory Used"
    }
   ]
  },
  {
   "title": "JVM 垃圾回收時間",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}