spring:
  application:
    name: metric-export-basic

server:
  port: 8080

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        # include: health,metrics,prometheus
        include: metrics,prometheus

    # health:
    #   show-details: always

    metrics:
      tags:
        application: ${spring.application.name}

      # Custom Metrics Configuration
      # enable:
      #   all: true
      #   jvm: true
        # process: true
      #   system: true
      #   logback: true
      #   tomcat: true
