version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/docker/rabbitmq/log/:/var/log/rabbitmq
    # networks:
    #     - rabbitmq_nodejs
# networks:
#   rabbitmq_nodejs:
#     driver: bridge