server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

rabbitmq:
  exchanges:
    state-machine: state-machine-exchange
  queues:
    tenant: tenant-state-queue
  routing-keys:
    tenant: tenant.state.#