spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/asimov
    username: root
    password: medusa
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
      # ddl-auto: validate
jwt:
  secret: your-secret-key
  expiration: 86400000
