spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 60000

jwt:
  secret: YourSecretKeyHereItShouldBeVeryLongAndRandomForSecurityReasons
  expirationMs: 86400000 # 24 hours
  refreshExpirationMs: 604800000 # 7 days
  cookieName: JWT_SESSION
  
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG
