{
 "title": "Race",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Capacity Unit (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time({app=\"race\"} | unwrap capacityUnit [1m])",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "avg_over_time({app=\"race\"} | unwrap consumedValue [1m])",
     "legendFormat": "Consumed Unit"
    }
   ]
  },
  {
   "title": "Sum of Request (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"race\"} |= `requestId` [1m]))"
    }
   ]
  },
  {
   "title": "Log Raw Data",
   "type": "logs",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=\"race\"} | json"
    }
   ]
  }
 ]
}