@API_PATH = http://localhost:8080

### ---- normal request
GET {{API_PATH}}/public


### ---- auth needed w/o token
GET {{API_PATH}}/auth-needed

### ---- auth needed w/ token
GET {{API_PATH}}/auth-needed
X-Auth-Token: 123