#@HOST = http://35.166.206.169:8080
@HOST = http://localhost:8080

### ----------------------------
POST {{ HOST }}/api/members
Content-Type: application/json

{
    "username": "user1",
    "password": "111",
    "authorities": ["STUDENT"]
}

### ----------------------------
POST {{ HOST }}/api/members
Content-Type: application/json

{
    "username": "user2",
    "password": "222",
    "authorities": ["TEACHER"]
}

### ----------------------------
POST {{ HOST }}/api/members
Content-Type: application/json

{
    "username": "user3",
    "password": "333",
    "authorities": ["TEACHER", "ADMIN"]
}