filebeat.inputs:
  - type: log
    paths:
      - /logs/stock*.log.json
    fields:
      app_name: stock-app
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    index: "stock"  # 自定義索引標記

  - type: log
    paths:
      - /logs/stock.consumer*.json
    fields:
      app_name: stock-app
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    index: "stock-consumer"  # 自定義索引標記

  - type: log
    paths:
      - /logs/stock.request*.json
    fields:
      app_name: stock-app
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    index: "stock-request"  # 自定義索引標記

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  indices:
    # - index: "capacity-%{+yyyy.MM.dd}"
    #   when.equals:
    #     index: "capacity"

    - index: "stock-%{+yyyy.MM.dd}"
      when.equals:
        index: "stock"

setup.kibana:
  host: "kibana:5601"

# 可選：自動設置索引模板
setup.template:
  name: "custom-filebeat"
  pattern: "stock-*"
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 1
