version: '3.8'
services:

  rdb_mariadb:
    image: mariadb:10.10
    environment:
      MARIADB_DATABASE: asimov
      MARIADB_ROOT_PASSWORD: medusa
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - ./.docker-data/rdb_mariadb:/var/lib/mysql
    networks:
      - net1

  rdb-adminer_phpmyadmin:
    image: phpmyadmin
    ports:
      - 9999:80
    links:
      - rdb_mariadb:db
    depends_on:
      rdb_mariadb:
        condition: service_healthy
    networks:
      - net1

networks:
  net1:
    driver: bridge
