{
 "title": "task-v4-20241215",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate_duration", "label": "Rate Duration", "query": "1m,5m,10m" },
   { "name": "range", "label": "range", "query": "30m,1h,3h,6h,12h,1d,3d,1w" }
  ]
 },
 "panels": [
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Status: range: [${range}]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tasks_creation_count_total[$range])",
     "legendFormat": "Creation"
    },
    {
     "expr": "increase(tasks_creation_count_total[$range]) - increase(tasks_completed_count_total[$range])",
     "legendFormat": "Proceesing"
    },
    {
     "expr": "increase(tasks_completed_count_total[$range])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Tasks Metric (increase by range: $range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(tasks_creation_count_total[$range])",
     "legendFormat": "Total Creation"
    },
    {
     "expr": "increase(tasks_completed_count_total[$range])",
     "legendFormat": "Total Completed"
    },
    {
     "expr": "increase(tasks_creation_count_total[$range]) - increase(tasks_completed_count_total[$range])",
     "legendFormat": "Proceesing"
    }
   ]
  },
  {
   "title": "Tasks Metric (Increamental)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "tasks_creation_count_total", "legendFormat": "Total Creation" },
    { "expr": "tasks_completed_count_total", "legendFormat": "Total Completed" },
    {
     "expr": "tasks_creation_count_total - tasks_completed_count_total",
     "legendFormat": "Proceesing"
    }
   ]
  },
  {
   "title": "Tasks Metric (Rate: $rate_duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(tasks_creation_count_total[$rate_duration])",
     "legendFormat": "Total Creation"
    },
    {
     "expr": "rate(tasks_completed_count_total[$rate_duration])",
     "legendFormat": "Total Completed"
    }
   ]
  },
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Task API 響應時間分布: [$rate_duration]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\"}[$rate_duration])",
     "legendFormat": "{{method}}:{{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\",  uri=\"/api/tasks\"}[$rate_duration])",
     "legendFormat": "GET:/api/tasks"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"DELETE\"}[$rate_duration])",
     "legendFormat": "{{method}}:{{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"PUT\"}[$rate_duration])",
     "legendFormat": "{{method}}:{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP 請求錯誤率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"5*\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}