server:
  port: 8080


# -----------------------------------------------------------------------------
# Sprinboot
# -----------------------------------------------------------------------------
# spring:

#   datasource:
#     url: jdbc:mysql://localhost:3306/asimov?allowPublicKeyRetrieval=true&useSSL=false
#     username: root
#     password: password

#   jpa:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQLDialect
#       ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    # operationsSorter: name

logging:
  level:
    com.gtcafe.app: DEBUG