spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
app:
  rabbitmq:
    tenant:
      queue: tenant-status-queue
      exchange: tenant-status-exchange
      routing-key: tenant.status
