# Docker Compose configuration for PGB4 Frontend development and testing
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production
        VITE_API_BASE_URL: http://localhost:8080/api/v1
        VITE_APP_NAME: "PGB4 Message Board"
        VITE_APP_VERSION: "1.0.0"
        VITE_APP_ENV: production
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - pgb4-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mock backend service for testing
  backend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./mock-backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pgb4-network
    restart: unless-stopped

networks:
  pgb4-network:
    driver: bridge