@API_PATH = http://localhost:8080/api/tokens
@TOKEN = 123

## lab01

### ---- json parsing error exception
POST {{API_PATH}}/
Content-Type: application/json
X-Auth-Token: {{TOKEN}}

{
    "tokenName": "app01",
    "appName": "webapi",
    "tenantId": 1,
}

###
POST {{API_PATH}}/
Content-Type: application/json
X-Auth-Token: {{TOKEN}}

{
    "tokenName": "app01",
    "appName": "webapi",
    "tenantId": 1
}

###
POST {{API_PATH}}/
Content-Type: application/json
X-Auth-Token: {{TOKEN}}

###
POST {{API_PATH}}/
Content-Type: application/json
X-Auth-Token: {{TOKEN}}

{
    "tokenName": "app01",
    "appName": "webapi"
}