@API_PATH = http://localhost:8080/api/tokens

### ---- lab01-4
GET {{API_PATH}}/name/rick/age/14?version=v1
X-Auth-Token: 123

### ---- lab01-4
GET {{API_PATH}}/name/---/age/14?version=v1
X-Auth-Token: 123

### ---- lab01-4
GET {{API_PATH}}/name/---/age/-4?version=v1
X-Auth-Token: 123