@API_PATH = http://localhost:8080/api/tokens

## ---- lab01-3: nested object
### normal case
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "kind": "app01",
    "metadata": {
        "name": "rick",
        "label": "123",
        "email": "rick@abc.com"
    }
}


### validation 1
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "kind": "app01"
}

### validation 1
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "kind": "a1234567890"
}

### validation 2
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "kind": "app01",
    "metadata": {

    }
}

### validation 3
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "metadata": {
        "name": "rick",
        "label": "123"
    }
}

### validation 4
POST {{API_PATH}}/nested-object
Content-Type: application/json

{

}


### validation 5
POST {{API_PATH}}/nested-object
Content-Type: application/json

{
    "kind": "app01",
    "metadata": {
        "name": "rick",
        "label": "123",
        "email": "rickcom"
    }
}